name: CI

on:
  push:
    branches: main

jobs:
  ci:
    runs-on: [self-hosted, noble, amd64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          pip install .
          lxd init --auto
          sudo snap install charmcraft --classic --channel latest/edge
          sudo snap install rockcraft --classic --channel latest/edge
          sudo snap install terraform --classic

          # Microk8s
          sudo snap install microk8s --channel 1.31-strict/stable
          sudo adduser $USER snap_microk8s
          newgrp snap_microk8s
          sudo microk8s enable hostpath-storage
          sudo microk8s enable registry
          sudo microk8s enable ingress

          # Juju
          sudo snap install juju
          mkdir -p ~/.local/share
          sudo microk8s status --wait-ready
          sg snap_microk8s -c 'juju bootstrap microk8s k8s-controller'
      - name: Deploy
        run: |
          cd app
          paas-charm deploy
      - name: Setup tmate session
        uses: canonical/action-tmate@main
