name: CI

on:
  push:
    branches: main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          pip install .
          lxd init --auto
          sudo snap install charmcraft --classic
          sudo snap install rockcraft --classic
      - name: deploy
        run: |
          cd app
          paas-charm deploy
