name: CI

on:
  push:
    branches: main

jobs:
  ci:
    runs-on: [self-hosted, noble, amd64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          pip install .
          lxd init --auto
          sudo snap install charmcraft --classic --channel latest/edge
          sudo snap install rockcraft --classic --channel latest/edge
          sudo snap install terraform --classic

          # Microk8s
          sudo snap install microk8s --channel 1.31-strict/stable
          sudo adduser $USER snap_microk8s
          newgrp snap_microk8s
          sudo microk8s enable hostpath-storage
          sudo microk8s enable registry
          sudo microk8s enable ingress

          # Juju
          sudo snap install juju
          mkdir -p ~/.local/share
          sudo microk8s status --wait-ready
          sg snap_microk8s -c 'juju bootstrap microk8s k8s-controller'
      - name: Deploy
        run: |
          cd app
          paas-charm deploy
          juju wait-for application sample-app
          juju wait-for application nginx-ingress-integrator
          curl http://sample-app --resolve sample-app:80:127.0.0.1 | grep 'Hello, world!'
          cd ..

          # Change to using database
          cp db-app/app.py app/
          cp db-app/migrate.py app/
          cp db-app/requirements.txt app/
          cp db-app/rockcraft.yaml app/
          cp db-app/charm/charmcraft.yaml app/charm/

          cd app
          paas-charm deploy
          juju wait-for application sample-app
          juju wait-for application nginx-ingress-integrator
          juju wait-for application postgresql-k8s
          curl http://sample-app/visitors --resolve sample-app:80:127.0.0.1 | grep '0'
          curl http://sample-app --resolve sample-app:80:127.0.0.1 | grep 'Hello, world!'
          curl http://sample-app/visitors --resolve sample-app:80:127.0.0.1 | grep '1'
          curl http://sample-app --resolve sample-app:80:127.0.0.1 | grep 'Hello, world!'
          curl http://sample-app/visitors --resolve sample-app:80:127.0.0.1 | grep '2'
